name: Security Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  sca:
    name: "SCA – Vulnerable NuGet Packages"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: SCA – Check vulnerable NuGet packages
        run: dotnet list package --vulnerable --include-transitive

  sast:
    name: "SAST – Semgrep Scan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: pip install semgrep

      - name: SAST – Semgrep Scan
        run: |
          semgrep scan \
            --config "SAST-Rules/sast-rules.yml" \
            --config "p/csharp" \
            --config "p/security-audit" \
            --error
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

  dast:
    name: "DAST – OWASP ZAP API Scan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
  
      - name: Restore dependencies
        run: dotnet restore
  
      - name: Publish Application
        # Команда publish соберет проект (автоматически найдет .csproj) и положит готовую DLL в папку ./out
        run: dotnet publish --configuration Debug --output ./out
  
      - name: Run application
        # Теперь мы точно знаем, где лежит файл, независимо от структуры папок
        run: |
          export ASPNETCORE_URLS="http://0.0.0.0:5000"
          export ASPNETCORE_ENVIRONMENT="Development"
          dotnet ./out/DevSecOps-Example.dll > app.log 2>&1 &
  
      - name: Wait for app to be ready
        run: |
          echo "Waiting for app..."
          for i in $(seq 1 20); do
            if curl -sf http://127.0.0.1:5000/openapi/v1.json > /dev/null; then
              echo "App is up and OpenAPI schema is ready!"
              exit 0
            fi
            echo "Attempt $i: App is not ready yet, retrying in 3s..."
            sleep 3
          done
          
          echo "=== APPLICATION LOGS ==="
          cat app.log
          echo "========================"
          echo "App did not start in time" && exit 1
  
      - name: DAST – OWASP ZAP API Scan
        run: |
          docker run --rm \
            --network host \
            -v "${PWD}:/zap/wrk/:rw" \
            zaproxy/zap-stable zap-api-scan.py \
              -t "http://127.0.0.1:5000/openapi/v1.json" \
              -f openapi \
              -c "/zap/wrk/ZAP-Rules/zap-rules.conf" \
              -I